@extends('layouts.main')

@section('scripts')
	@parent
	<script id="comment-genius" type="text/javascript" src="//192.168.14.148:8000/js/cg.js"></script>
@stop

@section('content')
	<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse eu massa magna, id faucibus elit. Sed rhoncus ante et nulla feugiat laoreet. In arcu lorem, auctor rhoncus malesuada non, viverra et ipsum. Nam lectus justo, hendrerit vitae eleifend a, facilisis at nisl. In hac habitasse platea dictumst. Sed tellus enim, ultrices non molestie vel, porttitor vel mauris. Sed luctus feugiat turpis vel laoreet. Quisque consectetur leo sed purus adipiscing luctus. Vivamus sed sem tortor, sed aliquam tellus. Aenean molestie lorem neque.</p>
	<p>Phasellus molestie odio dapibus lectus viverra posuere. Mauris turpis sem, blandit vitae viverra ac, fringilla et mi. Vivamus leo nisl, adipiscing fermentum varius et, faucibus nec erat. Vestibulum sit amet leo ligula, vel egestas orci. Maecenas nec lorem eget urna egestas varius. Sed euismod lobortis diam, a pretium mi cursus at. Nullam scelerisque mattis bibendum. Donec sapien orci, porta non tempor eu, pharetra ut est.</p>
	<p>Nullam sit amet ipsum nisl, vel lobortis justo. Donec facilisis lorem eu felis varius viverra pretium sit amet augue. Praesent venenatis molestie ligula at molestie. Phasellus eget lacus lectus, auctor dignissim ante. Praesent egestas, diam pharetra facilisis gravida, ligula ligula cursus libero, at dictum lacus nibh sit amet risus. Nam eget massa sed leo ullamcorper dignissim non ut arcu. Vivamus dapibus eleifend enim, sed consectetur est viverra non. Donec nec odio turpis, sed scelerisque nibh. Nulla ac massa massa, vitae sollicitudin neque. Phasellus molestie, arcu sit amet gravida scelerisque, justo urna varius sapien, faucibus venenatis massa urna vitae elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Morbi lorem quam, fringilla nec semper eu, cursus sit amet justo. Proin eleifend sagittis adipiscing. Fusce id lacus ante, eget tempus urna. Curabitur eu hendrerit purus.</p>
	<p>Maecenas nec augue quis neque placerat hendrerit. Sed tempus magna a nulla hendrerit adipiscing. Maecenas nibh ante, commodo ac suscipit quis, tempus ullamcorper metus. Curabitur tempus nisi vel ipsum dapibus ullamcorper pulvinar enim scelerisque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean convallis libero eu nibh vulputate semper. Praesent bibendum velit ac augue scelerisque a condimentum lectus sodales. In nec ligula massa, nec faucibus turpis. Aliquam consectetur faucibus venenatis. Vivamus non velit tellus, nec vehicula velit. Duis auctor mattis est, et convallis massa sagittis porta. Integer nec enim turpis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.</p>
	<p>Maecenas pharetra metus non urna ornare posuere posuere risus faucibus. Nunc ut nisl diam. Mauris sapien tellus, faucibus a viverra nec, ultrices ac risus. Vivamus nec lacus metus, at vulputate massa. Aenean interdum posuere turpis sed euismod. Nam malesuada viverra leo sed dapibus. Morbi porta leo eu velit sagittis porta. Duis gravida sem in leo varius fermentum tincidunt nulla rutrum. Nullam nulla urna, sodales ac mollis id, facilisis sit amet arcu. Quisque vehicula arcu ac felis pretium eu adipiscing magna scelerisque. Integer varius vehicula metus quis volutpat.</p>
@stop
